os:
  - linux

language: go
go:
  - "1.18"

services:
  - docker

env:
  global:
    # Required
    - OS=linux

stages:
  - test-frontend 

jobs:
  include:
    - stage: test-frontend 
      name: "Run frontend test"
      script:
        - |
          make clean
          make all
          make assets
          make apiv2
          git diff --exit-code
